
version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

      working_directory: ~/AndroidDemo

    steps:
    - checkout


    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "AndroidDemo/app" }}
        - v1-dependencies-

    - run: gradle dependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "AndroidDemo/app" }}


    - run: gradle test